version: "3"

services:
  web:
    build: .
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - .env

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
      
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles:ro
      - media_volume:/home/app/web/media:ro
    ports:
      - 8020:80


volumes:
  postgres_data:
  static_volume:
  media_volume: