# Generated by Django 4.2.23 on 2025-07-26 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='site/screenshots/')),
                ('caption', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logos/')),
                ('logo_footer', models.ImageField(blank=True, null=True, upload_to='site/logos/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/hero/')),
                ('widget_image', models.ImageField(blank=True, null=True, upload_to='site/widget/')),
                ('message_view_image', models.ImageField(blank=True, null=True, upload_to='site/message-view/')),
                ('instagram', models.URLField(blank=True, null=True)),
                ('whatsapp', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('screenshot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siteconfig_via', to='core.screenshot', verbose_name='Screenshot de destaque')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
        migrations.AddField(
            model_name='screenshot',
            name='siteconfig',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screenshot_obj', to='core.siteconfig'),
        ),
        migrations.CreateModel(
            name='HistoricalSiteConfig',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('logo', models.TextField(blank=True, max_length=100, null=True)),
                ('logo_footer', models.TextField(blank=True, max_length=100, null=True)),
                ('hero_image', models.TextField(blank=True, max_length=100, null=True)),
                ('widget_image', models.TextField(blank=True, max_length=100, null=True)),
                ('message_view_image', models.TextField(blank=True, max_length=100, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('whatsapp', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('screenshot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.screenshot', verbose_name='Screenshot de destaque')),
            ],
            options={
                'verbose_name': 'historical Configuração do Site',
                'verbose_name_plural': 'historical Configurações do Site',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
