# Generated by Django 4.2.23 on 2025-07-26 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='caption',
        ),
    ]
