# Generated by Django 4.2.23 on 2025-07-26 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_screenshot_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='siteconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='core.siteconfig'),
        ),
    ]
