# Generated by Django 4.2.23 on 2025-07-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_screenshot_siteconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsiteconfig',
            old_name='message_view_image',
            new_name='auto_image',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='message_view_image',
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='favicon',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='auto_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/images/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site/images/'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/images/'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/images/'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='logo_footer',
            field=models.ImageField(blank=True, null=True, upload_to='site/images/'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='widget_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/images/'),
        ),
    ]
