# Generated by Django 4.2.23 on 2025-07-29 14:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_message_view_image_historicalsiteconfig_auto_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do serviço', max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, help_text='Frase menor ou slogan do serviço', max_length=300, verbose_name='Subtítulo')),
                ('slug', models.SlugField(help_text='URL amigável (gerado automaticamente a partir do título)', max_length=200, unique=True, verbose_name='Slug')),
                ('icon_class', models.CharField(blank=True, help_text="Por exemplo: 'fas fa-robot' ou 'flaticon-puzzle'", max_length=100, verbose_name='Classe de Ícone')),
                ('excerpt', models.TextField(blank=True, help_text='Pequena descrição usada na listagem', verbose_name='Resumo')),
                ('body', ckeditor.fields.RichTextField(help_text='Texto completo, com formatação (CKEditor)', verbose_name='Conteúdo')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque para ocultar da página pública', verbose_name='Publicado')),
                ('order', models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição; menor vem primeiro', verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ('order', 'title'),
            },
        ),
    ]
