# Generated by Django 4.2.23 on 2025-07-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_siteservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteservice',
            name='tags',
        ),
        migrations.AddField(
            model_name='siteservice',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Separe as tags por vírgula', max_length=255, verbose_name='Tags'),
        ),
    ]
