# Generated by Django 4.2.23 on 2025-07-29 21:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_siteservice_tags_siteservice_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='about_body',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Texto livre (HTML simples) para a seção Sobre Nós', verbose_name='Corpo Sobre Nós'),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='about_image_1',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagem Sobre Nós 1'),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='about_image_2',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagem Sobre Nós 2'),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='about_title',
            field=models.CharField(blank=True, default='', help_text='Título apresentado na seção Sobre Nós', max_length=200, verbose_name='Título Sobre Nós'),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Palavras‑chave separadas por vírgula para SEO', max_length=255, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_body',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Texto livre (HTML simples) para a seção Sobre Nós', verbose_name='Corpo Sobre Nós'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='site/images/', verbose_name='Imagem Sobre Nós 1'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='site/images/', verbose_name='Imagem Sobre Nós 2'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_title',
            field=models.CharField(blank=True, default='', help_text='Título apresentado na seção Sobre Nós', max_length=200, verbose_name='Título Sobre Nós'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Palavras‑chave separadas por vírgula para SEO', max_length=255, verbose_name='Tags'),
        ),
    ]
