# Generated by Django 4.2.23 on 2025-07-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_historicalsiteconfig_about_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='meta_description',
            field=models.CharField(blank=True, default='', help_text='Descrição para <meta name="description"> e OG (até ~160 caracteres)', max_length=160, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='meta_title',
            field=models.CharField(blank=True, default='', help_text='Título para <title> e Open Graph (até ~60 caracteres)', max_length=60, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='meta_description',
            field=models.CharField(blank=True, default='', help_text='Descrição para <meta name="description"> e OG (até ~160 caracteres)', max_length=160, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='meta_title',
            field=models.CharField(blank=True, default='', help_text='Título para <title> e Open Graph (até ~60 caracteres)', max_length=60, verbose_name='Meta Title'),
        ),
    ]
