# Generated by Django 4.2.23 on 2025-07-29 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_historicalsiteconfig_about_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsiteconfig',
            name='about_title',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='about_title',
        ),
    ]
