# Generated by Django 4.2.23 on 2025-07-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_plan_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='slug',
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default=1, max_length=255, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('retail', 'Varejo'), ('technology', 'Tecnologia'), ('industry', 'Indústria'), ('health', 'Saúde'), ('educational', 'Educacional'), ('financial', 'Financeiro'), ('civil_construction', 'Construção Civil'), ('services', 'Serviços'), ('commerce', 'Comércio'), ('agriculture', 'Agricultura'), ('tourism', 'Turismo'), ('food', 'Alimentos'), ('automotive', 'Automotivo'), ('energy', 'Energia'), ('logistics', 'Logística'), ('others', 'Outros')], max_length=20, verbose_name='Tipo de empresa'),
        ),
    ]
