# Generated by Django 4.2.23 on 2025-07-28 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_updated_at_historicaluser_historicalplan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalplan',
            name='price',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price',
        ),
        migrations.AddField(
            model_name='historicalplan',
            name='extra_agent_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor cobrado por agente além do inclusos', max_digits=8, verbose_name='Preço por Agente Extra'),
        ),
        migrations.AddField(
            model_name='historicalplan',
            name='extra_inbox_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor cobrado por inbox além das inclusas', max_digits=8, verbose_name='Preço por Inbox Extra'),
        ),
        migrations.AddField(
            model_name='historicalplan',
            name='included_agents',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de agentes inclusos no plano', verbose_name='Agentes Incluídos'),
        ),
        migrations.AddField(
            model_name='historicalplan',
            name='included_inboxes',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de inboxes inclusas no plano', verbose_name='Inboxes Incluídas'),
        ),
        migrations.AddField(
            model_name='historicalplan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor da assinatura mensal', max_digits=8, verbose_name='Preço Mensal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalplan',
            name='yearly_price',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Valor da assinatura anual (geralmente com desconto)', max_digits=8, verbose_name='Preço Anual'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='extra_agent_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor cobrado por agente além do inclusos', max_digits=8, verbose_name='Preço por Agente Extra'),
        ),
        migrations.AddField(
            model_name='plan',
            name='extra_inbox_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor cobrado por inbox além das inclusas', max_digits=8, verbose_name='Preço por Inbox Extra'),
        ),
        migrations.AddField(
            model_name='plan',
            name='included_agents',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de agentes inclusos no plano', verbose_name='Agentes Incluídos'),
        ),
        migrations.AddField(
            model_name='plan',
            name='included_inboxes',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de inboxes inclusas no plano', verbose_name='Inboxes Incluídas'),
        ),
        migrations.AddField(
            model_name='plan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=150, help_text='Valor da assinatura mensal', max_digits=8, verbose_name='Preço Mensal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='yearly_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor da assinatura anual (geralmente com desconto)', max_digits=8, verbose_name='Preço Anual'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.plan', verbose_name='Plano'),
        ),
        migrations.AlterField(
            model_name='historicalplan',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição detalhada do plano', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='historicalplan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Apenas planos ativos são oferecidos no front-end', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='historicalplan',
            name='name',
            field=models.CharField(default=0, help_text='Nome comercial do plano (ex: Free, Standard, Premium)', max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalplan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Gratuito'), ('standard', 'Padrão'), ('premium', 'Premium'), ('business', 'Business')], db_index=True, max_length=20, verbose_name='Tipo de Plano'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição detalhada do plano', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Apenas planos ativos são oferecidos no front-end', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(help_text='Nome comercial do plano (ex: Free, Standard, Premium)', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Gratuito'), ('standard', 'Padrão'), ('premium', 'Premium'), ('business', 'Business')], max_length=20, unique=True, verbose_name='Tipo de Plano'),
        ),
    ]
