# Generated by Django 4.2.23 on 2025-07-28 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_historicalplan_price_remove_plan_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalplan',
            name='name',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='name',
        ),
    ]
