# Generated by Django 4.2.23 on 2025-07-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_historicalplan_name_remove_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplan',
            name='billing_price_id',
            field=models.CharField(blank=True, help_text='Use no gateway para criar/iniciar assinaturas; vazio=pago manual', max_length=255, null=True, verbose_name='ID de Preço (Stripe/PSP)'),
        ),
        migrations.AddField(
            model_name='historicalplan',
            name='requires_payment',
            field=models.BooleanField(default=True, help_text='Desmarque para planos gratuitos, sem cobrança automática', verbose_name='Requer Cobrança'),
        ),
        migrations.AddField(
            model_name='plan',
            name='billing_price_id',
            field=models.CharField(blank=True, help_text='Use no gateway para criar/iniciar assinaturas; vazio=pago manual', max_length=255, null=True, verbose_name='ID de Preço (Stripe/PSP)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='requires_payment',
            field=models.BooleanField(default=True, help_text='Desmarque para planos gratuitos, sem cobrança automática', verbose_name='Requer Cobrança'),
        ),
    ]
