# Generated by Django 4.2.23 on 2025-07-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_historicalplan_billing_price_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplan',
            name='is_plan_staff',
            field=models.BooleanField(default=False, help_text='Marque se este plano é um plano de equipe', verbose_name='Plano de Equipe'),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_plan_staff',
            field=models.BooleanField(default=False, help_text='Marque se este plano é um plano de equipe', verbose_name='Plano de Equipe'),
        ),
    ]
