# Generated by Django 4.2.23 on 2025-07-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_historicalplan_is_plan_staff_plan_is_plan_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Gratuito'), ('standard', 'Padrão'), ('premium', 'Premium'), ('business', 'Business')], max_length=20, verbose_name='Tipo de Plano'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Gratuito'), ('standard', 'Padrão'), ('premium', 'Premium'), ('business', 'Business')], max_length=20, verbose_name='Tipo de Plano'),
        ),
    ]
