# Generated by Django 4.2.23 on 2025-07-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_historicalplan_plan_type_alter_plan_plan_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalplan',
            name='plan_type',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='plan_type',
        ),
        migrations.AddField(
            model_name='historicalplan',
            name='name',
            field=models.CharField(default='', help_text='Nome do plano', max_length=100, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='plan',
            name='name',
            field=models.CharField(default='', help_text='Nome do plano', max_length=100, verbose_name='Nome'),
        ),
    ]
