# Generated by Django 4.2.23 on 2025-07-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_historicalplan_plan_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='billing_address',
            field=models.JSONField(blank=True, help_text='Endereço de cobrança da empresa', null=True, verbose_name='Endereço de cobrança'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='billing_address',
            field=models.JSONField(blank=True, help_text='Endereço de cobrança da empresa', null=True, verbose_name='Endereço de cobrança'),
        ),
    ]
