# Generated by Django 4.2.23 on 2025-07-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_company_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplan',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Marque se este plano é um plano favorito', verbose_name='Favorito'),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Marque se este plano é um plano favorito', verbose_name='Favorito'),
        ),
    ]
